### ISSUE TITLE
Update to Netstandard

### ISSUE THREAD

**Issue by tforkmann** [haf/Topshelf.FSharp#5]
Hi there,

I'm using Topshelf a lot and I really like to use it for DotNetCore apps.
I was wondering if there are any plans to update the Topshelf.FSharp project to netstandard?

Let me know your thoughts.

Thanks!

**Comment by haf** [comment]
Greetings,

This is mainly a single file, that I use to copy into projects I use.

If you are interested in the released nuget supporting netstandard, I welcome a PR.

Thank you.

**Comment by tforkmann** [comment]
Hey,

I added the FSharpApi.fs to my project and referenced the new TopShelf version with .Net Core support.
There are a lot of errors appearing because the referenced functions in the new .Net Core TopShelf version are different. 

Did you mean a different file then the FSharpApi.fs?

**Comment by haf** [comment]
I'm not sure of what errors you are getting. Can you give examples?

**Comment by ForNeVeR** [comment]
While I agree that it would be convenient to port this package to .NET Standard, I can't reproduce any errors. It seems to work well in my .NET Core 2.0 application.

I've installed the following into my `fsproj`:

```xml
<PackageReference Include="Topshelf" Version="4.1.0.117-develop" /> <!-- note the prerelease version! -->
<PackageReference Include="Topshelf.FSharp" Version="3.0.0" />
```

And it seems to just work on `netcoreapp2.0` (although Topshelf.FSharp gives a warning about .NET 4.6.1 package being installed onto a Core program).

@tforkmann, my hypothesis is that you're trying to run **release** Topshelf version on top of .NET Core. It will throw `TypeLoadException`s, but they aren't Topshelf.FSharp fault.

**Comment by tforkmann** [comment]
Can confirm!
It works for me too!

Thanks!
